### ISSUE TITLE
Please add a LICENSE or COPYING file

### ISSUE THREAD

**Issue by mithro** [AltOS-Rust/cm0-port#12]
Could you please add a LICENSE or COPYING file which describes the license that this code is avaliable under.

**Comment by mithro** [comment]
I assume it will probably be GPLv3 as that is what your https://github.com/AltOS-Rust/altos-rust repo seems to be under?

**Comment by RJ-Russell** [comment]
Yes. All the code in the AltOS-Rust organization is or will be licensed under GPLv3. We recently separated out the project into multiple repos and haven't had the time to update and/or add docs to the newer repos.

**Comment by dnseitz** [comment]
Fixed by #14
